### ISSUE TITLE
CommonJS + Browserify

### ISSUE THREAD

**Issue by dmwyatt** [logentries/le_js#33]
What's the appropriate way to use this with a CommonJS + Browserify setup?

Should I be including a script tag in my `index.html` for `le.js`, or should I `require("libs/le.js")` in every file I want to use it?  

Where should I be calling `LE.init()`?

**Comment by chrismatheson** [comment]
Although i have not done it personally yet, i believe you can `npm install le_js --save` and then `require("le.js")` 

after you have required the logger somewhere in your code you can call the `init()` function probably best doing it first thing.

subsequent require's will not need to call `init()`

**Comment by chrismatheson** [comment]
@dmwyatt did you mange to use le_je successfully in your browserify project ?

**Comment by m0wfo** [comment]
I'm going to close this- @dmwyatt if you have any subsequent issues / suggestions / fixes, feel free to open another issue :)
