### ISSUE TITLE
Power awareness

### ISSUE THREAD

**Issue by m0wfo** [logentries/le_js#4]
On mobile devices, it might be polite to temporarily persist logs to local storage instead of sending them down the wire when battery life is low. This is possible with the HTML5 [Battery API](https://developer.mozilla.org/en-US/docs/WebAPI/Battery_Status)

**Comment by m0wfo** [comment]
Will mark as *wontfix* for now- if websockets or similar are reintroduced, power saving may be a side-benefit

**Comment by bathos** [comment]
One possible problem with buffering data is that you can't* stop a user from navigating or closing the tab just because your app wants to do some xhr first. I suppose it depends a lot on the use case whether potential loss of events is acceptable.

* well, shouldn't...

**Comment by m0wfo** [comment]
@bathos yeah, we don't have any consistent retry/backoff policy in any of our client libs at the moment
