### ISSUE TITLE
Log level formatting

### ISSUE THREAD

**Issue by hfjallemark** [logentries/le_js#44]
Right now log level is hardcoded to use LOGLEVEL in uppercasing. Is there any way I can manually set that so that I can be consistent with how we do it in our server side logging?

**Comment by m0wfo** [comment]
@hfjallemark it's an easy enough fix but requires some server-side work on our side; bet thing to do is add a feature request to our [trello board](https://trello.com/b/ICckMDvF/logentries-feature-request).

**Comment by hfjallemark** [comment]
I actually found an easier way to log errors where I have full control over the message:

```coffeescript
(message, url, line, date, token) ->
    request = new XMLHttpRequest()
    request.open 'POST', "https://js.logentries.com/v1/logs/#{token}"
    request.send "#{date} | [Error] | #{message} | url=#{window.location.href}"
```

Thanks anyway, closing the issue.

**Comment by m0wfo** [comment]
@hfjallemark cool- just a heads-up that our JS API is not publicly documented and subject to change (although in practice this is unlikely)
