### ISSUE TITLE
Typos on the library setup page

### ISSUE THREAD

**Issue by dandv** [logentries/le_js#47]
![image](https://cloud.githubusercontent.com/assets/33569/8587230/ad370b1a-25ad-11e5-8554-eddffe9f3680.png)

**Comment by vilda** [comment]
Thanks @dandv, this has been flagged for quick fix!

**Comment by gearoidof** [comment]
Hey there, this managed to fall between the cracks, sorry. It's been fixed now, and will go into production soon.
