### ISSUE TITLE
JavaScript setup asks me to replace nonexistent variable

### ISSUE THREAD

**Issue by dandv** [logentries/le_js#49]
After adding a JavaScript logger, I get this:

![image](https://cloud.githubusercontent.com/assets/33569/8665293/1e4a130a-2997-11e5-985e-c81e4eb21f50.png)

It looks like the code was copy/pasted from [somewhere](https://logentries.com/doc/javascript/), and that comment needs to be removed because the replacement was already done.

**Comment by gearoidof** [comment]
Hey, thanks for pointing this out! It's committed to the code base, and should go live soon!
