### ISSUE TITLE
Access denied on IE11

### ISSUE THREAD

**Issue by lcalvy** [logentries/le_js#54]
Hi,

We have more than 100 error in production environnement when IE11 (Win7 & Win 8.1) calling this function

https://github.com/logentries/le_js/blob/master/src/le.js#L263

I can reproduce in development environment

here the stack trace
```javascript
Error Access is denied.

    dependencies.25681075a.js:61500:16 _apiCall
    dependencies.25681075a.js:61447:32 send
    dependencies.25681075a.js:61408:12 _rawLog
    dependencies.25681075a.js:61548:16 _log
    dependencies.25681075a.js:61562:16 error
    dependencies.25681075a.js:61630:16 error
    dependencies.25681075a.js:78770:24 d[e]
    dependencies.25681075a.js:83907:16 Anonymous function
    dependencies.25681075a.js:23431:14 k.prototype.$broadcast
    dependencies.25681075a.js:57014:8 Anonymous function
```

**Comment by vilda** [comment]
Hi @lcalvy, isn't it related to security zones? IE supports various setting which may limit access to external resources...

**Comment by lcalvy** [comment]
It's used demo an internet zone, on ssl domain.

**Comment by lcalvy** [comment]
Sorry, seems that IE11 have a different implementation of CORS and block POST over http when domain is from https. It's a wrong configuration on my side.
