### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by bpaul** [logentries/le_js#7]
Hopefully I am misunderstanding something... It's a little scary to me to embed our logging token in HTML/Javascript. What is to stop someone using our token (via telnet for example) to fill our logs with random spam?

Thanks,

Barry

**Comment by dandv** [comment]
Intercom uses a [secure mode](http://docs.intercom.io/configuring-Intercom/enable-secure-mode) with HMACs. Could provide inspiration.

**Comment by vilda** [comment]
Hi Dan, Intercom's approach solves a different issue - passing some value from client's server side to intercom's server side. Client is unable to a certain degree forge this fixed-size set of values. That's interesting idea which might be useful in some cases, but it's a very narrow use-case comparing to this ticket, which is mostly concerned about client-side.

Though if you believe you would find use for it I can implement it in our backend.
